# Generated by Django 5.2.7 on 2025-12-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator', models.CharField(choices=[('HeadHunter', 'HeadHunter'), ('SuperJob', 'SuperJob'), ('Rabota.ru', 'Rabota.ru')], max_length=50, verbose_name='Платформа')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('experience', models.CharField(choices=[('not_experience', 'Нет опыта'), ('1year', 'От 1 года'), ('3year', 'От 3 лет'), ('6year', 'От 6 лет'), ('10year', 'От 10 лет')], default='not_experience', max_length=100, verbose_name='Опыт работы')),
                ('education', models.CharField(choices=[('not_important', 'Не имеет значения'), ('secondary', 'среднее профессиональное образование'), ('higher', 'высшее образование'), ('half_higher', 'неполное высшее'), ('any', 'образование любое')], default='not_important', max_length=50, verbose_name='Образование')),
                ('employment', models.CharField(choices=[('not_specified', 'Не имеет значения'), ('full_day', 'Полная занятость'), ('no_full_day', 'Неполная занятость'), ('no_full_day', 'сменный график')], default='not_specified', max_length=100, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('not_specified', 'Не имеет значения'), ('5/2', '5/2'), ('2/2', '2/2'), ('15/15', '15/15'), ('20/10', '20/10')], default='not_specified', max_length=20, verbose_name='График работы')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
