# Generated by Django 5.2.7 on 2025-12-01 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacation',
            unique_together={('user', 'url')},
        ),
    ]
