# Generated by Django 5.2.7 on 2025-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_alter_vacation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранном'),
        ),
    ]
