# Generated by Django 5.2.7 on 2025-12-02 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_vacation_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('platforms', models.JSONField(default=list, verbose_name='Выбранные платформы')),
                ('total_results', models.IntegerField(default=0, verbose_name='Всего найдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancies', models.ManyToManyField(blank=True, related_name='search_queries', to='aggregator.vacation', verbose_name='Найденные вакансии')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'ordering': ['-created_at'],
            },
        ),
    ]
