# Generated by Django 5.2.7 on 2025-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='address',
            field=models.TextField(blank=True, default='Не указано', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='education',
            field=models.CharField(choices=[('not_important', 'Не имеет значения'), ('secondary', 'среднее профессиональное образование'), ('higher', 'высшее образование'), ('half_higher', 'неполное высшее'), ('any', 'образование любое')], default='Не имеет значения', max_length=50, verbose_name='Образование'),
        ),
    ]
